from enum import StrEnum

class CampaignStatus(StrEnum):
    CREATED="CREATED"; QUEUED="QUEUED"; GENERATING_STRATEGY="GENERATING_STRATEGY"; GENERATING_COPY="GENERATING_COPY"; GENERATING_STORYBOARD="GENERATING_STORYBOARD"; GENERATING_IMAGES="GENERATING_IMAGES"; RENDERING_VIDEO="RENDERING_VIDEO"; READY_FOR_REVIEW="READY_FOR_REVIEW"; REVISION_REQUESTED="REVISION_REQUESTED"; APPROVED="APPROVED"; FINAL="FINAL"; FAILED="FAILED"; CANCELLED="CANCELLED"
class WorkflowStep(StrEnum):
    STRATEGY="strategy"; COPY="copy"; STORYBOARD="storyboard"; IMAGES="images"; VOICEOVER="voiceover"; VIDEO="video"; PACKAGE="package"
class SQSOperation(StrEnum): START="START"; RESUME="RESUME"; REGENERATE="REGENERATE"
class ArtifactType(StrEnum):
    REFERENCE_IMAGE="REFERENCE_IMAGE"; IMAGE="IMAGE"; AUDIO="AUDIO"; VIDEO="VIDEO"; STORYBOARD="STORYBOARD"; MANIFEST="MANIFEST"; REVIEW_PACKAGE="REVIEW_PACKAGE"; FINAL_PACKAGE="FINAL_PACKAGE"; PROVIDER_DIAGNOSTIC="PROVIDER_DIAGNOSTIC"
class CampaignEventType(StrEnum):
    CAMPAIGN_CREATED="CAMPAIGN_CREATED"; JOB_QUEUED="JOB_QUEUED"; STATUS_CHANGED="STATUS_CHANGED"; STEP_STARTED="STEP_STARTED"; STEP_COMPLETED="STEP_COMPLETED"; STEP_REUSED="STEP_REUSED"; RETRY_SCHEDULED="RETRY_SCHEDULED"; PROVIDER_CALL_STARTED="PROVIDER_CALL_STARTED"; PROVIDER_CALL_COMPLETED="PROVIDER_CALL_COMPLETED"; PROVIDER_FALLBACK_USED="PROVIDER_FALLBACK_USED"; REVIEW_READY="REVIEW_READY"; REVISION_REQUESTED="REVISION_REQUESTED"; APPROVED="APPROVED"; FINALIZED="FINALIZED"; CANCEL_REQUESTED="CANCEL_REQUESTED"; CANCELLED="CANCELLED"; FAILED="FAILED"; LATE_PROVIDER_RESULT_DISCARDED="LATE_PROVIDER_RESULT_DISCARDED"
class ErrorComponent(StrEnum):
    FASTAPI="FASTAPI"; LANGGRAPH_WORKER="LANGGRAPH_WORKER"; MARKETING_MCP="MARKETING_MCP"; IMAGE_MCP="IMAGE_MCP"; HYPERFRAMES_MCP="HYPERFRAMES_MCP"; BEDROCK="BEDROCK"; DYNAMODB="DYNAMODB"; S3="S3"; SQS="SQS"; PACKAGER="PACKAGER"; UNKNOWN="UNKNOWN"
class RevisionTarget(StrEnum): STRATEGY="STRATEGY"; COPY="COPY"; STORYBOARD="STORYBOARD"; SELECTED_IMAGES="SELECTED_IMAGES"; VIDEO="VIDEO"
class StepStatus(StrEnum): PENDING="PENDING"; RUNNING="RUNNING"; SUCCEEDED="SUCCEEDED"; FAILED="FAILED"; REUSED="REUSED"; CANCELLED="CANCELLED"
class Actor(StrEnum): FASTAPI="FASTAPI"; LANGGRAPH_WORKER="LANGGRAPH_WORKER"; DEMO_USER="DEMO_USER"; SYSTEM="SYSTEM"
