from enum import StrEnum

class CampaignStatus(StrEnum):
    CREATED="CREATED"; QUEUED="QUEUED"; GENERATING_STRATEGY="GENERATING_STRATEGY"; GENERATING_COPY="GENERATING_COPY"; GENERATING_STORYBOARD="GENERATING_STORYBOARD"; GENERATING_IMAGES="GENERATING_IMAGES"; RENDERING_VIDEO="RENDERING_VIDEO"; READY_FOR_REVIEW="READY_FOR_REVIEW"; REVISION_REQUESTED="REVISION_REQUESTED"; APPROVED="APPROVED"; FINAL="FINAL"; FAILED="FAILED"; CANCELLED="CANCELLED"
class WorkflowStep(StrEnum):
    STRATEGY="strategy"; COPY="copy"; STORYBOARD="storyboard"; CREATIVE_PLAN="creative_plan"; IMAGES="images"; VOICEOVER="voiceover"; VIDEO="video"; PACKAGE="package"
class SQSOperation(StrEnum): START="START"; RESUME="RESUME"; REGENERATE="REGENERATE"
class ArtifactType(StrEnum):
    REFERENCE_IMAGE="REFERENCE_IMAGE"; IMAGE="IMAGE"; AUDIO="AUDIO"; VIDEO="VIDEO"; STORYBOARD="STORYBOARD"; MANIFEST="MANIFEST"; REVIEW_PACKAGE="REVIEW_PACKAGE"; FINAL_PACKAGE="FINAL_PACKAGE"; PROVIDER_DIAGNOSTIC="PROVIDER_DIAGNOSTIC"
class CampaignEventType(StrEnum):
    CAMPAIGN_CREATED="CAMPAIGN_CREATED"; JOB_QUEUED="JOB_QUEUED"; STATUS_CHANGED="STATUS_CHANGED"; STEP_STARTED="STEP_STARTED"; STEP_COMPLETED="STEP_COMPLETED"; STEP_REUSED="STEP_REUSED"; STEP_SKIPPED="STEP_SKIPPED"; RETRY_SCHEDULED="RETRY_SCHEDULED"; PROVIDER_CALL_STARTED="PROVIDER_CALL_STARTED"; PROVIDER_CALL_COMPLETED="PROVIDER_CALL_COMPLETED"; PROVIDER_FALLBACK_USED="PROVIDER_FALLBACK_USED"; REVIEW_READY="REVIEW_READY"; REVISION_REQUESTED="REVISION_REQUESTED"; APPROVED="APPROVED"; FINALIZED="FINALIZED"; CANCEL_REQUESTED="CANCEL_REQUESTED"; CANCELLED="CANCELLED"; FAILED="FAILED"; LATE_PROVIDER_RESULT_DISCARDED="LATE_PROVIDER_RESULT_DISCARDED"
class ErrorComponent(StrEnum):
    FASTAPI="FASTAPI"; LANGGRAPH_WORKER="LANGGRAPH_WORKER"; MARKETING_MCP="MARKETING_MCP"; IMAGE_MCP="IMAGE_MCP"; HYPERFRAMES_MCP="HYPERFRAMES_MCP"; BEDROCK="BEDROCK"; DYNAMODB="DYNAMODB"; S3="S3"; SQS="SQS"; PACKAGER="PACKAGER"; UNKNOWN="UNKNOWN"
class RevisionTarget(StrEnum): STRATEGY="STRATEGY"; COPY="COPY"; STORYBOARD="STORYBOARD"; SELECTED_IMAGES="SELECTED_IMAGES"; VIDEO="VIDEO"
class VideoStyle(StrEnum): VOICEOVER_AD="VOICEOVER_AD"; CINEMATIC_TEXT_AD="CINEMATIC_TEXT_AD"; MUSIC_FIRST_REEL="MUSIC_FIRST_REEL"
class ShotRole(StrEnum):
    HOOK="HOOK"; PRODUCT_HERO="PRODUCT_HERO"; ACTION="ACTION"; DETAIL="DETAIL"; LIFESTYLE="LIFESTYLE"; MESSAGE="MESSAGE"; PAYOFF="PAYOFF"; CTA="CTA"
class AssetRole(StrEnum):
    HERO_PRODUCT="HERO_PRODUCT"; ACTION_SHOT="ACTION_SHOT"; DETAIL_SHOT="DETAIL_SHOT"; LIFESTYLE_PRODUCT="LIFESTYLE_PRODUCT"; CTA_FRAME="CTA_FRAME"
class CameraMotion(StrEnum):
    STATIC="STATIC"; PUSH_IN="PUSH_IN"; PULL_OUT="PULL_OUT"; PAN_LEFT="PAN_LEFT"; PAN_RIGHT="PAN_RIGHT"; PAN_UP="PAN_UP"; PAN_DOWN="PAN_DOWN"; MACRO_PUSH="MACRO_PUSH"; SCALE_THROUGH="SCALE_THROUGH"
class TransitionType(StrEnum):
    CUT="CUT"; CROSSFADE="CROSSFADE"; WIPE="WIPE"; MASK_REVEAL="MASK_REVEAL"; SCALE_THROUGH="SCALE_THROUGH"; MOTION_MATCH="MOTION_MATCH"
class AudioCueType(StrEnum):
    TRANSITION_HIT="TRANSITION_HIT"; IMPACT="IMPACT"; WHOOSH="WHOOSH"; BRAND_HIT="BRAND_HIT"; ICE_CLINK="ICE_CLINK"
class StepStatus(StrEnum): PENDING="PENDING"; RUNNING="RUNNING"; SUCCEEDED="SUCCEEDED"; FAILED="FAILED"; REUSED="REUSED"; SKIPPED="SKIPPED"; CANCELLED="CANCELLED"
class Actor(StrEnum): FASTAPI="FASTAPI"; LANGGRAPH_WORKER="LANGGRAPH_WORKER"; DEMO_USER="DEMO_USER"; SYSTEM="SYSTEM"
