/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/campaigns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Campaigns */
    get: operations['list_campaigns_api_v1_campaigns_get']
    put?: never
    /** Create Campaign */
    post: operations['create_campaign_api_v1_campaigns_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/campaigns/{campaign_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Campaign */
    get: operations['get_campaign_api_v1_campaigns__campaign_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Live */
    get: operations['live_health_live_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ready */
    get: operations['ready_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ApprovalRecord */
    ApprovalRecord: {
      /**
       * Actor
       * @default DEMO_USER
       */
      actor: string
      /**
       * Approval Id
       * Format: uuid
       */
      approval_id: string
      /**
       * Approved At
       * Format: date-time
       */
      approved_at: string
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string
      /** Campaign Version */
      campaign_version: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Decision
       * @default APPROVED
       */
      decision: string
      /**
       * Lock Version
       * @default 1
       */
      lock_version: number
      /** Manifest Checksum */
      manifest_checksum: string
      /** Note */
      note?: string | null
    }
    /**
     * ArtifactType
     * @enum {string}
     */
    ArtifactType:
      | 'REFERENCE_IMAGE'
      | 'IMAGE'
      | 'AUDIO'
      | 'VIDEO'
      | 'STORYBOARD'
      | 'MANIFEST'
      | 'REVIEW_PACKAGE'
      | 'FINAL_PACKAGE'
      | 'PROVIDER_DIAGNOSTIC'
    /** CampaignCopy */
    CampaignCopy: {
      /** Call To Action */
      call_to_action: string
      /** Caption */
      caption: string
      /** Channel Variants */
      channel_variants: components['schemas']['ChannelCopy'][]
      /** Hashtags */
      hashtags: string[]
      /** Headline */
      headline: string
    }
    /** CampaignCreationAcceptedResponse */
    CampaignCreationAcceptedResponse: {
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string
      /** Campaign Version */
      campaign_version: number
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string
      /** Links */
      links: {
        [key: string]: string
      }
      /** Progress Percent */
      progress_percent: number
      status: components['schemas']['CampaignStatus']
    }
    /** CampaignCreationRequest */
    CampaignCreationRequest: {
      /** Brand Colors */
      brand_colors?: string[]
      /** Business Description */
      business_description: string
      /** Business Name */
      business_name: string
      /** Call To Action */
      call_to_action?: string | null
      /** Campaign Goal */
      campaign_goal: string
      /** Key Message */
      key_message?: string | null
      /** Language */
      language: string
      /** Platforms */
      platforms: string[]
      /** Product Or Service */
      product_or_service: string
      /** Reference Artifact Id */
      reference_artifact_id?: string | null
      /** Target Audience */
      target_audience?: string | null
      /** Tone */
      tone: string
    }
    /** CampaignDetailResponse */
    CampaignDetailResponse: {
      /** Actions */
      actions?: {
        [key: string]: string
      }
      approval?: components['schemas']['ApprovalRecord'] | null
      /** Artifacts */
      artifacts?: components['schemas']['PublicArtifactReference'][]
      brief: components['schemas']['NormalizedCampaignBrief']
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string
      /** Campaign Version */
      campaign_version: number
      /** Completed Steps */
      completed_steps?: components['schemas']['WorkflowStep'][]
      copy?: components['schemas']['CampaignCopy'] | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      current_step?: components['schemas']['WorkflowStep'] | null
      /** Current Version */
      current_version: number
      error?: components['schemas']['SanitizedWorkflowError'] | null
      /** Event Sequence */
      event_sequence: number
      /** Latest Final Version */
      latest_final_version?: number | null
      /** Progress Percent */
      progress_percent: number
      /** Retry Eligible */
      retry_eligible: boolean
      revision?: components['schemas']['RevisionFeedback'] | null
      status: components['schemas']['CampaignStatus']
      storyboard?: components['schemas']['Storyboard'] | null
      strategy?: components['schemas']['StrategyOutput'] | null
      /** Title */
      title: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** CampaignListResponse */
    CampaignListResponse: {
      /** Items */
      items: components['schemas']['CampaignSummary'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /**
     * CampaignStatus
     * @enum {string}
     */
    CampaignStatus:
      | 'CREATED'
      | 'QUEUED'
      | 'GENERATING_STRATEGY'
      | 'GENERATING_COPY'
      | 'GENERATING_STORYBOARD'
      | 'GENERATING_IMAGES'
      | 'RENDERING_VIDEO'
      | 'READY_FOR_REVIEW'
      | 'REVISION_REQUESTED'
      | 'APPROVED'
      | 'FINAL'
      | 'FAILED'
      | 'CANCELLED'
    /** CampaignSummary */
    CampaignSummary: {
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      current_step?: components['schemas']['WorkflowStep'] | null
      /** Current Version */
      current_version: number
      /** Latest Final Version */
      latest_final_version?: number | null
      /** Progress Percent */
      progress_percent: number
      status: components['schemas']['CampaignStatus']
      /** Title */
      title: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** ChannelCopy */
    ChannelCopy: {
      /** Call To Action */
      call_to_action: string
      /** Caption */
      caption: string
      /** Channel */
      channel: string
      /** Hashtags */
      hashtags: string[]
      /** Headline */
      headline: string
    }
    /** ConflictError */
    ConflictError: {
      error: components['schemas']['SanitizedWorkflowError']
    }
    /**
     * ErrorComponent
     * @enum {string}
     */
    ErrorComponent:
      | 'FASTAPI'
      | 'LANGGRAPH_WORKER'
      | 'MARKETING_MCP'
      | 'IMAGE_MCP'
      | 'HYPERFRAMES_MCP'
      | 'BEDROCK'
      | 'DYNAMODB'
      | 'S3'
      | 'SQS'
      | 'PACKAGER'
      | 'UNKNOWN'
    /** HealthResponse */
    HealthResponse: {
      /** Environment */
      environment: string
      /** Service */
      service: string
      /** Status */
      status: string
    }
    /** NormalizedCampaignBrief */
    NormalizedCampaignBrief: {
      /** Brand Colors */
      brand_colors?: string[]
      /** Business Description */
      business_description: string
      /** Business Name */
      business_name: string
      /** Call To Action */
      call_to_action?: string | null
      /** Campaign Goal */
      campaign_goal: string
      /** Key Message */
      key_message?: string | null
      /** Language */
      language: string
      /** Platforms */
      platforms: string[]
      /** Product Or Service */
      product_or_service: string
      /** Reference Artifact Id */
      reference_artifact_id?: string | null
      /** Target Audience */
      target_audience?: string | null
      /** Tone */
      tone: string
    }
    /** NotFoundError */
    NotFoundError: {
      error: components['schemas']['SanitizedWorkflowError']
    }
    /** ProviderStatus */
    ProviderStatus: {
      /** Category */
      category: string
      /** Http Status */
      http_status?: number | null
      /** Provider */
      provider: string
      /** Provider Code */
      provider_code?: string | null
    }
    /** PublicArtifactReference */
    PublicArtifactReference: {
      /**
       * Artifact Id
       * Format: uuid
       */
      artifact_id: string
      artifact_type: components['schemas']['ArtifactType']
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string
      /** Campaign Version */
      campaign_version: number
      /** Checksum Sha256 */
      checksum_sha256: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Mime Type */
      mime_type: string
      /** Provider */
      provider?: string | null
      /** Size Bytes */
      size_bytes: number
      workflow_step: components['schemas']['WorkflowStep']
    }
    /** RevisionFeedback */
    RevisionFeedback: {
      /** Affected Artifact Ids */
      affected_artifact_ids?: string[]
      earliest_affected_step: components['schemas']['WorkflowStep']
      /** Parent Version */
      parent_version: number
      /** Reason */
      reason: string
      scope: components['schemas']['RevisionTarget']
    }
    /**
     * RevisionTarget
     * @enum {string}
     */
    RevisionTarget: 'STRATEGY' | 'COPY' | 'STORYBOARD' | 'SELECTED_IMAGES' | 'VIDEO'
    /** SanitizedWorkflowError */
    SanitizedWorkflowError: {
      /** Attempt */
      attempt: number
      /** Campaign Id */
      campaign_id?: string | null
      /** Campaign Version */
      campaign_version?: number | null
      /** Code */
      code: string
      component: components['schemas']['ErrorComponent']
      /**
       * Correlation Id
       * Format: uuid
       */
      correlation_id: string
      /** Job Id */
      job_id?: string | null
      /** Message */
      message: string
      provider_status?: components['schemas']['ProviderStatus'] | null
      /** Retryable */
      retryable: boolean
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string
      workflow_step?: components['schemas']['WorkflowStep'] | null
    }
    /** StandardValidationError */
    StandardValidationError: {
      error: components['schemas']['SanitizedWorkflowError']
    }
    /** Storyboard */
    Storyboard: {
      /** Scenes */
      scenes: components['schemas']['StoryboardScene'][]
      /** Total Duration Seconds */
      total_duration_seconds: number
    }
    /** StoryboardScene */
    StoryboardScene: {
      /** Duration Seconds */
      duration_seconds: number
      /** Narration */
      narration: string
      /** Purpose */
      purpose: string
      /** Scene Number */
      scene_number: number
      /**
       * Text Overlay
       * @default
       */
      text_overlay: string
      /** Transition */
      transition: string
      /** Visual Prompt */
      visual_prompt: string
    }
    /** StrategyOutput */
    StrategyOutput: {
      /** Audience */
      audience: string
      /** Channel Rationale */
      channel_rationale: {
        [key: string]: string
      }
      /** Key Message */
      key_message: string
      /** Objective */
      objective: string
      /** Positioning */
      positioning: string
    }
    /**
     * WorkflowStep
     * @enum {string}
     */
    WorkflowStep: 'strategy' | 'copy' | 'storyboard' | 'images' | 'video' | 'package'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_campaigns_api_v1_campaigns_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignListResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StandardValidationError']
        }
      }
    }
  }
  create_campaign_api_v1_campaigns_post: {
    parameters: {
      query?: never
      header: {
        'Idempotency-Key': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignCreationRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignCreationAcceptedResponse']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConflictError']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StandardValidationError']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StandardValidationError']
        }
      }
    }
  }
  get_campaign_api_v1_campaigns__campaign_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        campaign_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignDetailResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotFoundError']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StandardValidationError']
        }
      }
    }
  }
  live_health_live_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  ready_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
