from abc import ABC, abstractmethod
from uuid import UUID

from campaign_contracts.campaign import ApprovalRecord, CampaignAggregateMetadata, CampaignVersion


class CampaignRepository(ABC):
    @abstractmethod
    async def create_initial(self, aggregate: CampaignAggregateMetadata, version: CampaignVersion) -> None: ...
    @abstractmethod
    async def get(self, campaign_id: UUID) -> tuple[CampaignAggregateMetadata, CampaignVersion] | None: ...
    @abstractmethod
    async def list(self, *, offset: int, limit: int) -> list[tuple[CampaignAggregateMetadata, CampaignVersion]]: ...
    @abstractmethod
    async def exists(self, campaign_id: UUID) -> bool: ...
    @abstractmethod
    async def replace_current(self, aggregate: CampaignAggregateMetadata, version: CampaignVersion) -> None: ...
    @abstractmethod
    async def approve(
        self, aggregate: CampaignAggregateMetadata, version: CampaignVersion, approval: ApprovalRecord
    ) -> None: ...
    @abstractmethod
    async def cancel(self, aggregate: CampaignAggregateMetadata, version: CampaignVersion) -> None: ...
    @abstractmethod
    async def retry(self, aggregate: CampaignAggregateMetadata, version: CampaignVersion) -> None: ...
    @abstractmethod
    async def revise(
        self,
        aggregate: CampaignAggregateMetadata,
        parent_version: CampaignVersion,
        child_version: CampaignVersion,
    ) -> None: ...
    @abstractmethod
    async def rollback_initial(self, campaign_id: UUID) -> None: ...
    @abstractmethod
    async def available(self) -> bool: ...
    @abstractmethod
    async def clear(self) -> None: ...
